### ISSUE TITLE
No 'close' function on Cursor

### ISSUE THREAD

**Issue by Wildsoft** [wereHamster/rethinkdb-client-driver#7]
No sure if it is really an issue , just wanted to confirm what is the right way to release Cursor obtained to receive change feeds (changes). There is no close method on Cursor (https://www.rethinkdb.com/api/javascript/close-cursor/) so for now I just spawn thread in which I invoke each function. When I no longer need changesfeed I cancel the thread. My concern is that it would cause resource leak if cursor is not released correctly at that point. Thanks.

**Comment by wereHamster** [comment]
I don't remember adding support for cursors or feeds to this driver.

**Comment by Wildsoft** [comment]
Sorry, I confused this project with https://github.com/atnnn/haskell-rethinkdb; Closing
